### ISSUE TITLE
Multiple Issues in step 4

### ISSUE THREAD

**Issue by forestcolat** [madelinegannon/example-mediapipe-udp#5]
I am a beginner, so I do not understand very well waht does this means. I am doing this in Visual Studio 2017 on Windows 10, so I do not know i some problems are because of the fact that you are doing this in a Mac. This is the Error:

PS C:\Users\orest> cd C:\Users\orest\mediapipe_repo\mediapipe
PS C:\Users\orest\mediapipe_repo\mediapipe> bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1     mediapipe/examples/
desktop/hand_tracking:hand_tracking_cpu
Starting local Bazel server and connecting to it...
INFO: Repository local_execution_config_python instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule local_python_configure defined at:
  C:/users/orest/_bazel_orest/6wjl4ovg/external/org_tensorflow/third_party/py/python_configure.bzl:275:41: in <toplevel
>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/orest/_bazel_orest/6wjl4ovg/external/org_tensorflow/third_party/py/python_configure.bzl", line 2
10
                _get_python_lib(repository_ctx, <1 more arguments>)
        File "C:/users/orest/_bazel_orest/6wjl4ovg/external/org_tensorflow/third_party/py/python_configure.bzl", line 1
30, in _get_python_lib
                execute(repository_ctx, <1 more arguments>)
        File "C:/users/orest/_bazel_orest/6wjl4ovg/external/org_tensorflow/third_party/remote_config/common.bzl", line
208, in execute
                fail(<1 more arguments>)
Repository command failed
File "<string>", line 1
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
ERROR: Analysis of target '//mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu' failed; build aborted: Traceba
ck (most recent call last):
        File "C:/users/orest/_bazel_orest/6wjl4ovg/external/org_tensorflow/third_party/py/python_configure.bzl", line 2
10
                _get_python_lib(repository_ctx, <1 more arguments>)
        File "C:/users/orest/_bazel_orest/6wjl4ovg/external/org_tensorflow/third_party/py/python_configure.bzl", line 1
30, in _get_python_lib
                execute(repository_ctx, <1 more arguments>)
        File "C:/users/orest/_bazel_orest/6wjl4ovg/external/org_tensorflow/third_party/remote_config/common.bzl", line
208, in execute
                fail(<1 more arguments>)
Repository command failed
File "<string>", line 1
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
INFO: Elapsed time: 11.561s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (11 packages loaded, 11 targets configured)

**Comment by madelinegannon** [comment]
Hi @forestcolat — I feel your frustration! Let's try to get around this hurdle together. 

It seems like your hunch is correct, and the windows style file path is causing the [error](https://stackoverflow.com/questions/1347791/unicode-error-unicodeescape-codec-cant-decode-bytes-cannot-open-text-file). But before you do any more debugging, I suggest that you try to get mediapipe running using google's [Windows Installation Instructions](https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows). 

If you can get their Hello World example working, I think you'll be in good shape for adapting (i.e., copy/paste) the code from this repo for your windows setup. Keep me posted with your progress!

**Comment by GTron-1729** [comment]
Hello Madeline, as per the windows instructions it has a disclaimer as;
Disclaimer: Running MediaPipe on Windows is experimental.

Note: building MediaPipe Android apps is still not possible on native Windows. Please do this in WSL ( windows subsystem for Linux ) instead and see the WSL setup instruction in the next section.

So, should I proceed with windows or should I proceed with WSL?

**Comment by madelinegannon** [comment]
I don't have direct experience with WSL, but following along with what the MediaPipe project suggests seems prudent. Plus, they'll have more answers and support for WSL in their repo.
